#!/bin/bash

exit_cpm {
    printf "\n\e[32m==============================================================\e[0m\n"
    rm out_file
}

trap exit_cpm SIGINT

cpp_file=$1
out_file=${cpp_file%.*}

params="-std=c++14 -Wall -Wextra -pedantic -O2 -Wshadow 
-Wformat=2 -Wfloat-equal -Wconversion -Wlogical-op 
-Wshift-overflow=2 -Wduplicated-cond -Wcast-qual 
-Wcast-align -D_GLIBCXX_DEBUG -D_GLIBCXX_DEBUG_PEDANTIC 
-D_FORTIFY_SOURCE=2 -fsanitize=address 
-fsanitize=undefined -fno-sanitize-recover 
-fstack-protector -Wstack-usage=100000000"

if g++ $cpp_file $params -o $out_file; then 
    printf "\e[32m==============================================================\e[0m\n"
    START=$(date +%s.%N)
    ./$out_file
    END=$(date +%s.%N)
    DIFF=$(echo "$END - $START" | bc)
    printf "\n\e[32m==============================================================\e[0m\n"
    printf "\e[32mExecution time: %s s\e[0m\n" $DIFF
    rm out_file
fi

exit 0